DELETE FROM public.products p
WHERE NOT EXISTS (SELECT 1 FROM public.order_items oi WHERE oi.product_id = p.id);

UPDATE public.products SET is_active = false, is_featured = false, updated_at = now();

INSERT INTO public.products (name, slug, short_description, description, benefits, price, billing_label, duration_days, category_id, image_url, is_active, is_featured) VALUES
('Netflix Premium', 'netflix-premium', 'Perfil privado en calidad 4K Ultra HD, con tu propio PIN.', 'Cuenta Netflix Premium con perfil individual y PIN personal. Disfruta películas, series y documentales en calidad 4K Ultra HD sin interrupciones.', ARRAY['Calidad 4K Ultra HD + HDR', 'Perfil privado con PIN', 'Sin anuncios', 'Funciona en TV, celular y PC', 'Garantía durante toda la suscripción'], 4.50, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/netflix.jpg', true, true),
('Disney+ Premium', 'disney-plus-premium', 'Películas y series de Disney, Pixar, Marvel, Star Wars y más.', 'Cuenta Disney+ Premium con perfil individual. Todo el catálogo de Disney, Pixar, Marvel, Star Wars y National Geographic en alta definición.', ARRAY['Perfil privado con PIN', 'Calidad Full HD / 4K', 'Catálogo completo Disney y Marvel', 'Descargas offline', 'Garantía durante toda la suscripción'], 3.75, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/disney.jpg', true, false),
('HBO Max', 'hbo-max', 'Series y películas exclusivas de HBO, Warner y DC.', 'Cuenta HBO Max con perfil individual. Estrenos de Warner Bros., series de HBO, DC y mucho más, listos para maratonear.', ARRAY['Perfil privado con PIN', 'Estrenos exclusivos de HBO', 'Calidad Full HD / 4K', 'Funciona en TV, celular y PC', 'Garantía durante toda la suscripción'], 3.50, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/hbomax.jpg', true, true),
('Prime Video', 'prime-video', 'Películas, series y Amazon Originals en Full HD.', 'Cuenta Prime Video con perfil individual. Disfruta Amazon Originals, películas de estreno y series exclusivas en todos tus dispositivos.', ARRAY['Perfil privado con PIN', 'Amazon Originals incluidos', 'Calidad Full HD / 4K', 'Funciona en TV, celular y PC', 'Garantía durante toda la suscripción'], 3.25, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/primevideo.jpg', true, false),
('Paramount+', 'paramount-plus', 'Series, películas y deportes en vivo de Paramount.', 'Cuenta Paramount+ con perfil individual. Series exclusivas, películas de Paramount Pictures, fútbol en vivo y contenido para toda la familia.', ARRAY['Perfil privado con PIN', 'Deportes en vivo', 'Estrenos de Paramount', 'Calidad Full HD', 'Garantía durante toda la suscripción'], 2.75, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/paramount.jpg', true, false),
('ViX Premium', 'vix-premium', 'El mejor contenido en español: novelas, series y fútbol.', 'Cuenta ViX Premium con perfil individual. Novelas, series originales en español, películas y fútbol en vivo sin anuncios.', ARRAY['Perfil privado con PIN', 'Contenido 100% en español', 'Fútbol y deportes en vivo', 'Sin anuncios', 'Garantía durante toda la suscripción'], 2.50, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/vix.jpg', true, false),
('Pack LoMaximoLeo — 6 plataformas', 'pack-lomaximoleo', 'Netflix + Disney+ + HBO Max + Prime Video + Paramount+ + ViX.', 'El combo definitivo: las 6 plataformas de streaming en un solo paquete con precio especial. Perfiles privados con PIN en cada plataforma y soporte prioritario.', ARRAY['Las 6 plataformas incluidas', 'Perfiles privados con PIN', 'Ahorra más de $4 al mes', 'Soporte prioritario', 'Garantía durante toda la suscripción'], 15.99, 'mensual', 30, '761168f9-268b-4fc9-985a-d9709274b6d7', '/images/products/combo.jpg', true, true);